### ISSUE TITLE
Allow ordering at install time.

### ISSUE THREAD

**Issue by captncraig** [caddyserver/caddyext#1]
I would really like to add extensions like I do with caddydev, specifying where in the stack to insert it after.

How about `caddyext install name path/to/name directiveToPlaceAfter`?

**Comment by captncraig** [comment]
This saves the trouble of needing to move things after I install it.

**Comment by pedronasser** [comment]
Was thinking something like -a (-after) and -b (-before)
Example:
```
caddyext install extension [repository] -a gzip
caddyext install extension [repository] -b gzip
```
@captncraig what do you think?

**Comment by mholt** [comment]
I think you'd only need one of them, like -after, right?

**Comment by pedronasser** [comment]
@mholt right, just -after would be enough

**Comment by captncraig** [comment]
unless you wanted to put it at the top of the stack. I like your syntax
better though for sure.

**Comment by mholt** [comment]
Well I think the caddydev tool places it at the beginning if -after is empty. But yeah, either way, sounds good to me.

**Comment by pedronasser** [comment]
Done. @61ff02033d96628208eff9652b4fc8bf1fe627d5
Could you please test it?
