### ISSUE TITLE
Missing deleting line when install extension

### ISSUE THREAD

**Issue by Unknwon** [caddyserver/caddyext#4]
In the latest version (with `go get -u`),

after I execute `caddyext install git:xxx`, it deletes the line `"github.com/mholt/caddy/caddy/https"` in the file `caddy/directives.go` which make Caddy main repo can't compile anymore.

**Comment by pedronasser** [comment]
I guess I know what is the issue.
Every time caddy updates its directives.go structure we must update its template on this repo.
I'll fix that.

**Comment by Unknwon** [comment]
:+1:

**Comment by mholt** [comment]
My bad! Maybe someday we'll have a way that doesn't require this.
