### ISSUE TITLE
Unable to build caddy v0.8.x with plugins/extensions in Alpine Linux

### ISSUE THREAD

**Issue by smyrman** [caddyserver/caddyext#9]
Using one of:
- https://github.com/jumanjihouse/docker-caddy
- https://gist.github.com/smyrman/3737cb37c0fac87c832041361e4db89d

I am not able to build caddy when installing extensions:
```
$ caddyext install git     # Also tried prometheus and jwt (one at a time and combined)
$ caddyext build /go/bin
```
Instead, I get the following error from the caddyext build step:
```
$ make
....
`caddyext build` error: exit status 1
Usage:
  caddyext build [output path] [flags]
```
where as I would expect no errors and customCaddy to be compiled. Building caddy without extensions appears to work, and produce the correct binary.

PS! It's quite confusing to get the usage information printed when the error does not seam to relate to invalid or malformed input parameters. It would be much better if the error message could be improved, and only show the usage information (and return error code 2) if the command has the wrong number, or non-understandable input parameters.

**Comment by smyrman** [comment]
I should also add that this used to work some weeks ago..

**Comment by mholt** [comment]
Yeah, Caddy 0.9 breaks things and we're transitioning through the beta period right now. Those tools have been upgraded in the meantime but you'll have to download (or check out) an older revision of caddyext to build plugins with Caddy 0.8.x - note that you'll also need to check out older revisions of (most of) the plugins as well.

Sorry for the inconvenience. Hoping to get everything synchronized again soon!
